//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synkron.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class SynkronEntities : DbContext
    {
        public SynkronEntities()
            : base("name=SynkronEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Frequency> Frequency { get; set; }
        public virtual DbSet<Status> Status { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<TaskManage> TaskManage { get; set; }
    
        public virtual ObjectResult<usp_GetAllTasks_Result> usp_GetAllTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllTasks_Result>("usp_GetAllTasks");
        }
    
        public virtual ObjectResult<usp_GetTaskByStatus_Result> usp_GetTaskByStatus(Nullable<int> statusId)
        {
            var statusIdParameter = statusId.HasValue ?
                new ObjectParameter("StatusId", statusId) :
                new ObjectParameter("StatusId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetTaskByStatus_Result>("usp_GetTaskByStatus", statusIdParameter);
        }
    
        public virtual ObjectResult<usp_GetUnassignedTasks_Result> usp_GetUnassignedTasks()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetUnassignedTasks_Result>("usp_GetUnassignedTasks");
        }
    
        public virtual ObjectResult<usp_GetAllTaskManage_Result> usp_GetAllTaskManage()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_GetAllTaskManage_Result>("usp_GetAllTaskManage");
        }
    }
}
