//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Synkron.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskManage
    {
        public int ID { get; set; }
        public Nullable<int> TaskID { get; set; }
        public Nullable<int> FrequencyID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    
        public virtual Frequency Frequency { get; set; }
        public virtual Task Task { get; set; }
    }
}
